import os
import io
import math
import traceback
from datetime import datetime
import pandas as pd
from flask import request, send_file, redirect, flash
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import mm
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    HRFlowable, KeepTogether
)
from reportlab.pdfgen import canvas
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont


# ── BRAND COLORS ────────────────────────────────────────────
C_ACCENT      = colors.HexColor("#185fa5")   # brand blue
C_ACCENT_LIGHT= colors.HexColor("#e6f1fb")
C_BG          = colors.HexColor("#f5f4f0")   # off-white bg
C_CARD        = colors.white
C_BORDER      = colors.HexColor("#e0ddd5")
C_TEXT        = colors.HexColor("#111110")
C_TEXT2       = colors.HexColor("#6b6a67")
C_TEXT3       = colors.HexColor("#a09f9b")
C_SUCCESS     = colors.HexColor("#2d6a11")
C_SUCCESS_BG  = colors.HexColor("#eaf3de")
C_WARN        = colors.HexColor("#854f0b")
C_WARN_BG     = colors.HexColor("#faeeda")
C_DANGER      = colors.HexColor("#a32d2d")
C_DANGER_BG   = colors.HexColor("#fcebeb")
C_WHITE       = colors.white

PAGE_W, PAGE_H = A4
MARGIN = 18 * mm


# ── WATERMARK CANVAS ────────────────────────────────────────
class WatermarkCanvas(canvas.Canvas):
    """Draws a diagonal 'CleanSight' watermark + header/footer on every page."""

    def __init__(self, filename, **kwargs):
        super().__init__(filename, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        total = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self._draw_watermark()
            self._draw_header()
            self._draw_footer(self._pageNumber, total)
            canvas.Canvas.showPage(self)
        canvas.Canvas.save(self)

    def _draw_watermark(self):
        self.saveState()
        self.setFont("Helvetica-Bold", 52)
        self.setFillColor(colors.HexColor("#185fa5"))
        self.setFillAlpha(0.04)
        self.translate(PAGE_W / 2, PAGE_H / 2)
        self.rotate(35)
        # Repeat across diagonal
        for y_off in [-260, -130, 0, 130, 260]:
            self.drawCentredString(0, y_off, "CleanSight")
        self.restoreState()

    def _draw_header(self):
        self.saveState()
        # Header bar
        self.setFillColor(C_ACCENT)
        self.rect(0, PAGE_H - 14*mm, PAGE_W, 14*mm, fill=1, stroke=0)
        # Logo text
        self.setFillColor(C_WHITE)
        self.setFont("Helvetica-Bold", 11)
        self.drawString(MARGIN, PAGE_H - 9*mm, "CleanSight")
        self.setFont("Helvetica", 9)
        self.drawString(MARGIN + 70, PAGE_H - 9*mm, "Data Quality Report")
        # Date on right
        date_str = datetime.now().strftime("%d %b %Y")
        self.drawRightString(PAGE_W - MARGIN, PAGE_H - 9*mm, date_str)
        self.restoreState()

    def _draw_footer(self, page_num, total):
        self.saveState()
        # Footer line
        self.setStrokeColor(C_BORDER)
        self.setLineWidth(0.5)
        self.line(MARGIN, 12*mm, PAGE_W - MARGIN, 12*mm)
        self.setFont("Helvetica", 8)
        self.setFillColor(C_TEXT3)
        self.drawString(MARGIN, 8*mm, "Generated by CleanSight AI Platform")
        self.drawRightString(PAGE_W - MARGIN, 8*mm, f"Page {page_num} of {total}")
        self.restoreState()


# ── STYLE HELPERS ────────────────────────────────────────────
def make_styles():
    base = getSampleStyleSheet()

    styles = {
        "report_title": ParagraphStyle(
            "report_title",
            fontName="Helvetica-Bold",
            fontSize=22,
            textColor=C_TEXT,
            leading=28,
            spaceAfter=4,
        ),
        "report_sub": ParagraphStyle(
            "report_sub",
            fontName="Helvetica",
            fontSize=10,
            textColor=C_TEXT2,
            leading=14,
            spaceAfter=0,
        ),
        "section_heading": ParagraphStyle(
            "section_heading",
            fontName="Helvetica-Bold",
            fontSize=11,
            textColor=C_TEXT,
            leading=16,
            spaceBefore=6,
            spaceAfter=6,
        ),
        "mono_label": ParagraphStyle(
            "mono_label",
            fontName="Courier",
            fontSize=8,
            textColor=C_TEXT3,
            leading=12,
        ),
        "body": ParagraphStyle(
            "body",
            fontName="Helvetica",
            fontSize=9.5,
            textColor=C_TEXT,
            leading=14,
        ),
        "reco": ParagraphStyle(
            "reco",
            fontName="Helvetica",
            fontSize=9.5,
            textColor=C_TEXT,
            leading=14,
            leftIndent=6,
        ),
        "score_big": ParagraphStyle(
            "score_big",
            fontName="Helvetica-Bold",
            fontSize=28,
            textColor=C_TEXT,
            leading=32,
            alignment=TA_CENTER,
        ),
        "score_label": ParagraphStyle(
            "score_label",
            fontName="Helvetica",
            fontSize=8,
            textColor=C_TEXT2,
            leading=11,
            alignment=TA_CENTER,
        ),
        "kpi_val": ParagraphStyle(
            "kpi_val",
            fontName="Helvetica-Bold",
            fontSize=18,
            textColor=C_TEXT,
            leading=22,
            alignment=TA_CENTER,
        ),
        "kpi_lbl": ParagraphStyle(
            "kpi_lbl",
            fontName="Helvetica",
            fontSize=8,
            textColor=C_TEXT3,
            leading=11,
            alignment=TA_CENTER,
        ),
        "table_header": ParagraphStyle(
            "table_header",
            fontName="Helvetica-Bold",
            fontSize=8,
            textColor=C_WHITE,
            alignment=TA_CENTER,
        ),
        "table_cell": ParagraphStyle(
            "table_cell",
            fontName="Courier",
            fontSize=8.5,
            textColor=C_TEXT,
            alignment=TA_CENTER,
        ),
        "tag": ParagraphStyle(
            "tag",
            fontName="Helvetica-Bold",
            fontSize=7.5,
            textColor=C_WHITE,
            alignment=TA_CENTER,
        ),
    }
    return styles


# ── KPI CARDS ROW ────────────────────────────────────────────
def kpi_row(df, styles):
    """Returns a Table acting as a row of KPI cards."""
    rows     = len(df)
    cols     = len(df.columns)
    missing  = int(df.isnull().sum().sum())
    dupes    = int(df.duplicated().sum())
    num_cols = int(df.select_dtypes(include="number").shape[1])
    txt_cols = int(df.select_dtypes(include="object").shape[1])

    def card(val, label, color=C_TEXT):
        s = styles["kpi_val"]
        colored = ParagraphStyle(
            "kpi_val_c", parent=s, textColor=color
        )
        return [
            Paragraph(str(val), colored),
            Paragraph(label, styles["kpi_lbl"]),
        ]

    data = [[
        card(rows,     "Total Rows"),
        card(cols,     "Columns"),
        card(missing,  "Missing", C_WARN if missing > 0 else C_SUCCESS),
        card(dupes,    "Duplicates", C_DANGER if dupes > 0 else C_SUCCESS),
        card(num_cols, "Numeric", C_ACCENT),
        card(txt_cols, "Text"),
    ]]

    col_w = (PAGE_W - 2*MARGIN) / 6
    t = Table(data, colWidths=[col_w]*6, rowHeights=None)
    t.setStyle(TableStyle([
        ("BOX",           (0,0), (-1,-1), 0.5, C_BORDER),
        ("INNERGRID",     (0,0), (-1,-1), 0.5, C_BORDER),
        ("BACKGROUND",    (0,0), (-1,-1), C_CARD),
        ("TOPPADDING",    (0,0), (-1,-1), 10),
        ("BOTTOMPADDING", (0,0), (-1,-1), 10),
        ("LEFTPADDING",   (0,0), (-1,-1), 6),
        ("RIGHTPADDING",  (0,0), (-1,-1), 6),
        ("ROUNDEDCORNERS",(0,0), (-1,-1), 4),
        ("VALIGN",        (0,0), (-1,-1), "MIDDLE"),
    ]))
    return t


# ── QUALITY SCORE CARD ───────────────────────────────────────
def quality_card(score, styles):
    if score >= 80:
        grade, color, grade_text = "A", C_SUCCESS, "Excellent"
    elif score >= 60:
        grade, color, grade_text = "B", C_WARN, "Good"
    elif score >= 40:
        grade, color, grade_text = "C", C_WARN, "Fair"
    else:
        grade, color, grade_text = "D", C_DANGER, "Poor"

    score_style = ParagraphStyle(
        "qs", fontName="Helvetica-Bold", fontSize=22,
        textColor=color, leading=36, alignment=TA_CENTER
    )
    grade_style = ParagraphStyle(
        "qg", fontName="Helvetica-Bold", fontSize=11,
        textColor=color, leading=14, alignment=TA_CENTER
    )
    label_style = ParagraphStyle(
        "ql", fontName="Helvetica", fontSize=8,
        textColor=C_TEXT2, leading=12, alignment=TA_CENTER
    )

    inner = Table(
        [[
            Paragraph(f"{score}", score_style),
            
        ]],
        colWidths=[90],
    )
    inner.setStyle(TableStyle([
        ("VALIGN", (0,0), (-1,-1), "BOTTOM"),
        ("LEFTPADDING", (0,0), (-1,-1), 0),
        ("RIGHTPADDING", (0,0), (-1,-1), 0),
        ("TOPPADDING", (0,0), (-1,-1), 0),
        ("BOTTOMPADDING", (0,0), (-1,-1), 0),
    ]))

    card_data = [[
        inner,
        [
            Paragraph(grade_text, grade_style),
            Spacer(1, 3),
            Paragraph("Data Quality Score", label_style),
            Spacer(1, 3),
            Paragraph("AI-assessed dataset health", label_style),
        ],
    ]]

    avail_w = PAGE_W - 2*MARGIN
    t = Table(card_data, colWidths=[100, avail_w - 100])
    t.setStyle(TableStyle([
        ("BOX",           (0,0), (-1,-1), 0.5, C_BORDER),
        ("BACKGROUND",    (0,0), (-1,-1), C_CARD),
        ("TOPPADDING",    (0,0), (-1,-1), 14),
        ("BOTTOMPADDING", (0,0), (-1,-1), 14),
        ("LEFTPADDING",   (0,0), (-1,-1), 18),
        ("RIGHTPADDING",  (0,0), (-1,-1), 14),
        ("VALIGN",        (0,0), (-1,-1), "MIDDLE"),
        ("LINEAFTER",     (0,0), (0,-1),  0.5, C_BORDER),
    ]))
    return t


# ── SECTION DIVIDER ──────────────────────────────────────────
def section_header(title, icon_char, styles):
    """Returns a styled section header row."""
    label_style = ParagraphStyle(
        "sh", fontName="Helvetica-Bold", fontSize=10,
        textColor=C_ACCENT, leading=14
    )
    avail_w = PAGE_W - 2*MARGIN
    t = Table(
        [[Paragraph(f"▸  {title}", label_style)]],
        colWidths=[avail_w],
    )
    t.setStyle(TableStyle([
        ("BACKGROUND",    (0,0), (-1,-1), C_ACCENT_LIGHT),
        ("TOPPADDING",    (0,0), (-1,-1), 7),
        ("BOTTOMPADDING", (0,0), (-1,-1), 7),
        ("LEFTPADDING",   (0,0), (-1,-1), 10),
        ("RIGHTPADDING",  (0,0), (-1,-1), 10),
        ("BOX",           (0,0), (-1,-1), 0.5, C_BORDER),
    ]))
    return t


# ── MISSING TABLE ────────────────────────────────────────────
def missing_table(missing_data, styles):
    avail_w = PAGE_W - 2*MARGIN

    header = [
        Paragraph("Column", styles["table_header"]),
        Paragraph("Missing Count", styles["table_header"]),
        Paragraph("Missing %", styles["table_header"]),
        Paragraph("Severity", styles["table_header"]),
    ]

    rows = [header]
    for col, count, pct_str in missing_data:
        pct = float(pct_str.replace("%", ""))
        if pct >= 50:
            sev_text, sev_color, sev_bg = "HIGH", C_WHITE, C_DANGER
        elif pct >= 20:
            sev_text, sev_color, sev_bg = "MED", C_WHITE, C_WARN
        else:
            sev_text, sev_color, sev_bg = "LOW", C_WHITE, C_SUCCESS

        sev_style = ParagraphStyle(
            "sev", fontName="Helvetica-Bold", fontSize=7.5,
            textColor=sev_color, alignment=TA_CENTER
        )
        col_style = ParagraphStyle(
            "colname", fontName="Courier-Bold", fontSize=8.5,
            textColor=C_ACCENT
        )
        rows.append([
            Paragraph(col, col_style),
            Paragraph(str(count), styles["table_cell"]),
            Paragraph(pct_str, styles["table_cell"]),
            Paragraph(sev_text, sev_style),
        ])

    col_widths = [avail_w * 0.40, avail_w * 0.22, avail_w * 0.22, avail_w * 0.16]
    t = Table(rows, colWidths=col_widths, repeatRows=1)

    style_cmds = [
        ("BACKGROUND",    (0,0), (-1,0),  C_ACCENT),
        ("TEXTCOLOR",     (0,0), (-1,0),  C_WHITE),
        ("FONTNAME",      (0,0), (-1,0),  "Helvetica-Bold"),
        ("FONTSIZE",      (0,0), (-1,0),  8),
        ("BOTTOMPADDING", (0,0), (-1,0),  8),
        ("TOPPADDING",    (0,0), (-1,0),  8),
        ("INNERGRID",     (0,0), (-1,-1), 0.4, C_BORDER),
        ("BOX",           (0,0), (-1,-1), 0.5, C_BORDER),
        ("TOPPADDING",    (0,1), (-1,-1), 7),
        ("BOTTOMPADDING", (0,1), (-1,-1), 7),
        ("LEFTPADDING",   (0,0), (-1,-1), 10),
        ("RIGHTPADDING",  (0,0), (-1,-1), 10),
        ("VALIGN",        (0,0), (-1,-1), "MIDDLE"),
        ("ROWBACKGROUNDS",(0,1), (-1,-1), [C_CARD, C_BG]),
    ]

    # Color-code severity cell background
    for i, (_, _, pct_str) in enumerate(missing_data, start=1):
        pct = float(pct_str.replace("%", ""))
        bg = C_DANGER_BG if pct >= 50 else (C_WARN_BG if pct >= 20 else C_SUCCESS_BG)
        style_cmds.append(("BACKGROUND", (3, i), (3, i), bg))

    t.setStyle(TableStyle(style_cmds))
    return t


# ── RECOMMENDATIONS ──────────────────────────────────────────
def reco_table(recommendations, styles):
    avail_w = PAGE_W - 2*MARGIN
    rows = []

    for rec in recommendations:
        rec_lower = rec.lower()
        if any(k in rec_lower for k in ["invalid", "error", "negative", "critical"]):
            sev, sev_color, bg = "CRITICAL", C_DANGER, C_DANGER_BG
        elif any(k in rec_lower for k in ["missing", "inconsistent", "mixed", "duplicate"]):
            sev, sev_color, bg = "WARNING", C_WARN, C_WARN_BG
        else:
            sev, sev_color, bg = "INFO", C_ACCENT, C_ACCENT_LIGHT

        icon = "✦"
        text_style = ParagraphStyle(
            "rec_body", fontName="Helvetica", fontSize=9,
            textColor=C_TEXT, leading=13
        )
        sev_style = ParagraphStyle(
            "rec_sev", fontName="Helvetica-Bold", fontSize=7.5,
            textColor=sev_color, alignment=TA_CENTER
        )

        rows.append([
            Paragraph(icon, ParagraphStyle(
                "icon", fontName="Helvetica-Bold", fontSize=10,
                textColor=sev_color, alignment=TA_CENTER
            )),
            Paragraph(rec, text_style),
            Paragraph(sev, sev_style),
        ])

    if not rows:
        rows = [[
            Paragraph("", styles["body"]),
            Paragraph("No recommendations — dataset looks clean!", styles["body"]),
            Paragraph("", styles["body"]),
        ]]

    col_widths = [avail_w * 0.06, avail_w * 0.72, avail_w * 0.22]
    t = Table(rows, colWidths=col_widths)

    style_cmds = [
        ("BOX",           (0,0), (-1,-1), 0.5, C_BORDER),
        ("INNERGRID",     (0,0), (-1,-1), 0.4, C_BORDER),
        ("TOPPADDING",    (0,0), (-1,-1), 8),
        ("BOTTOMPADDING", (0,0), (-1,-1), 8),
        ("LEFTPADDING",   (0,0), (-1,-1), 8),
        ("RIGHTPADDING",  (0,0), (-1,-1), 8),
        ("VALIGN",        (0,0), (-1,-1), "MIDDLE"),
    ]

    for i, rec in enumerate(recommendations):
        rec_lower = rec.lower()
        if any(k in rec_lower for k in ["invalid", "error", "negative", "critical"]):
            bg = C_DANGER_BG
        elif any(k in rec_lower for k in ["missing", "inconsistent", "mixed", "duplicate"]):
            bg = C_WARN_BG
        else:
            bg = C_ACCENT_LIGHT
        style_cmds.append(("BACKGROUND", (0, i), (-1, i), bg))
        style_cmds.append(("BACKGROUND", (2, i), (2, i), C_CARD))

    t.setStyle(TableStyle(style_cmds))
    return t
# ── MAIN ROUTE ───────────────────────────────────────────────

def generate_pdf_report(filename, cleaned_folder,
                        quality_engine,
                        recommendation_engine):
    try:
        filename = request.args.get("filename")
        cleaned_path = os.path.join(cleaned_folder, "cleaned_" + filename)
        df = pd.read_csv(cleaned_path)

        quality_score   = quality_engine(df)
        recommendations = recommendation_engine(df)

        # Missing report
        missing_data = []
        for col in df.columns:
            count = df[col].isnull().sum()
            if count > 0:
                pct = round((count / len(df)) * 100, 2)
                missing_data.append([col, count, f"{pct}%"])

        # PDF path
        pdf_path = os.path.join(
            cleaned_folder,
            "report_" + filename.replace(".csv", ".pdf")
        )

        # ── BUILD DOC ───────────────────────────────────────
        doc = SimpleDocTemplate(
            pdf_path,
            pagesize=A4,
            leftMargin=MARGIN,
            rightMargin=MARGIN,
            topMargin=22*mm,
            bottomMargin=20*mm,
        )

        styles   = make_styles()
        elements = []
        avail_w  = PAGE_W - 2*MARGIN

        # ── TITLE BLOCK ─────────────────────────────────────
        elements.append(Spacer(1, 6))
        elements.append(Paragraph("Data Quality Report", styles["report_title"]))
        elements.append(Paragraph(
            f"Dataset: <b>{filename}</b> &nbsp;·&nbsp; Generated: {datetime.now().strftime('%d %b %Y, %H:%M')}",
            styles["report_sub"]
        ))
        elements.append(Spacer(1, 14))
        elements.append(HRFlowable(
            width=avail_w, thickness=0.5,
            color=C_BORDER, spaceAfter=14
        ))

        # ── QUALITY SCORE ────────────────────────────────────
        elements.append(section_header("Quality Score", "", styles))
        elements.append(Spacer(1, 8))
        elements.append(quality_card(quality_score, styles))
        elements.append(Spacer(1, 16))

        # ── KPI CARDS ────────────────────────────────────────
        elements.append(section_header("Dataset Overview", "", styles))
        elements.append(Spacer(1, 8))
        elements.append(kpi_row(df, styles))
        elements.append(Spacer(1, 16))

        # ── MISSING REPORT ───────────────────────────────────
        elements.append(section_header("Missing Value Report", "", styles))
        elements.append(Spacer(1, 8))
        if missing_data:
            elements.append(missing_table(missing_data, styles))
        else:
            no_miss = Table(
                [[Paragraph("✓  No missing values found — dataset is complete!", ParagraphStyle(
                    "ok", fontName="Helvetica", fontSize=9.5, textColor=C_SUCCESS
                ))]],
                colWidths=[avail_w],
            )
            no_miss.setStyle(TableStyle([
                ("BACKGROUND",    (0,0), (-1,-1), C_SUCCESS_BG),
                ("BOX",           (0,0), (-1,-1), 0.5, C_SUCCESS),
                ("TOPPADDING",    (0,0), (-1,-1), 10),
                ("BOTTOMPADDING", (0,0), (-1,-1), 10),
                ("LEFTPADDING",   (0,0), (-1,-1), 12),
            ]))
            elements.append(no_miss)
        elements.append(Spacer(1, 16))

        # ── AI RECOMMENDATIONS ───────────────────────────────
        elements.append(section_header("AI Recommendations", "", styles))
        elements.append(Spacer(1, 8))
        elements.append(reco_table(recommendations, styles))
        elements.append(Spacer(1, 16))

        # ── FOOTER NOTE ──────────────────────────────────────
        elements.append(HRFlowable(
            width=avail_w, thickness=0.5,
            color=C_BORDER, spaceBefore=6
        ))
        elements.append(Spacer(1, 6))
        elements.append(Paragraph(
            "This report was generated automatically by CleanSight AI. "
            "Results are based on the cleaned version of your dataset.",
            ParagraphStyle(
                "footer_note", fontName="Helvetica", fontSize=8,
                textColor=C_TEXT3, leading=12
            )
        ))

        # ── BUILD WITH WATERMARK CANVAS ──────────────────────
        doc.build(elements, canvasmaker=WatermarkCanvas)

        return pdf_path

    except Exception:
        print(traceback.format_exc())
        flash("PDF generation failed.", "danger")
        return redirect("/")
